### ISSUE TITLE
DOCS: Google Analytics/Tag Manager pages 404

### ISSUE THREAD

**Issue by danawoodman** [DavidWells/analytics#38] opened 2020-04-10 17:29 UTC
These links seem dead (come from sidebar):

* https://getanalytics.io/plugins/google-analytics/
* https://getanalytics.io/plugins/google-tag-manager/

**Comment by DavidWells** [comment] 2020-04-13 01:20
Hey @danawoodman thanks for the report 😃

Those links are live, it's possible that your browser (brave) or an adblocker is blocking these URLs because they have these analytic tool names in the URL.

Can you verify this is the case?

**Comment by tammaroivan** [comment] 2020-04-13 15:10
I have the same problem in Brave. If you disable the shield it works fine 😄 

The weird thing is that the problem is happening only on those links

**Comment by DavidWells** [comment] 2020-04-13 15:29
Yeah I’ve heard this before. Brave is very aggressive at blocking any URL with word analytics in it. I wish these false positives weren’t a thing 🤪

Going to close this out but I sincerely appreciate the broken URL report!

**Closed as completed by DavidWells** 2020-04-13 15:29 UTC

**Comment by danawoodman** [comment] 2020-04-18 21:12
Wow, that's surprising Brave would do that but glad it wasn't some larger issue. Thanks 👍
